//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirportInformation
    {
        public int InformationID { get; set; }
        public System.DateTime InformationDate { get; set; }
        public int QuantityOfPlanesInUsage { get; set; }
        public int QuantityOfPlanesInMaintain { get; set; }
        public int QuantityOfPlanesAtApron { get; set; }
        public int QuantityOfPlanesOnAir { get; set; }
        public string ScheduledFlights { get; set; }
        public string Pilot { get; set; }
        public int AirlineCompanyID { get; set; }
    
        public virtual AirlineCompany AirlineCompany { get; set; }
    }
}
