//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApronInformation
    {
        public int InformationID { get; set; }
        public string Report { get; set; }
        public int Availability { get; set; }
        public int TerminalID { get; set; }
    
        public virtual AirportTerminal AirportTerminal { get; set; }
    }
}
