//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarparkAndSecuritiesInfo
    {
        public int InfoID { get; set; }
        public string Availabilty { get; set; }
        public string CurrentWorkerInfo { get; set; }
        public string FullnessRatio { get; set; }
        public decimal TotalCost { get; set; }
        public string CarparkWorkerList { get; set; }
        public string EntranceSecurityList { get; set; }
        public string VipSecurityInfo { get; set; }
        public int CarparkID { get; set; }
    
        public virtual Carpark Carpark { get; set; }
    }
}
