//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carpark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carpark()
        {
            this.CarparkAndSecuritiesInfoes = new HashSet<CarparkAndSecuritiesInfo>();
        }
    
        public int CarParkID { get; set; }
        public string ParkCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarparkAndSecuritiesInfo> CarparkAndSecuritiesInfoes { get; set; }

        public override string ToString()
        {
            return ParkCode;
        }
    }
}
