//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityInfo
    {
        public int SecurityID { get; set; }
        public string CabinNumber { get; set; }
        public System.DateTime InfoDate { get; set; }
        public string Report { get; set; }
    }
}
