//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicUnitInfo
    {
        public int UnitInfosID { get; set; }
        public string AircraftCodes { get; set; }
        public string FullnessRatio { get; set; }
        public string YearsOfAircraft { get; set; }
        public string PreviousMaintainAircraft { get; set; }
        public string Cost { get; set; }
        public int TechnicUnitID { get; set; }
    
        public virtual TechnicUnit TechnicUnit { get; set; }
    }
}
